version: "3.9"
services:
  backend:
    container_name: backend
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./core:/app
    environment:
      - SECRET_KEY=test
      - DEBUG=True
    expose:
      - 8000