# Generated by Django 3.2.1 on 2022-12-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_actvie',
            new_name='is_active',
        ),
    ]
